### ISSUE TITLE
WATTS Vision

### ISSUE THREAD

**Issue by daenney** [hemphen/homeassistant-clevertouch#9]
I was doing some research on the Tempco Touch E3 on my own, and came across the "Watts Water BT-CT02-RF" which looks awfully familiar :D. I almost wonder if that's the original and everyone else just licensed the thing from them.

They seem to be running the CleverTouch backend for what they're calling "WATTS Vision" on: https://smarthome.wattselectronics.com. It seems identical to all the other ones, same demo mode etc. too, API calls look the same. I don't have a way to actually test it since I don't own a central controller by WATTS, but I figured it might be of interest to you.

**Comment by hemphen** [comment]
Thank you for the update! I came across Watts Vision myself when researching support for my Purmo/LVI system.

The Watts backend has an improved authentication method compared to the brands supported by my implementation and I have no way to test it.

Also, Watts Vision support in home assistant already has a quite active community at [pwesters/watts_vision](https://github.com/pwesters/watts_vision). Support is probably also better than in this repo due to larger user base and potentially more types of compatible products.

**Comment by daenney** [comment]
Ah, I didn't know that! Thanks for the info
